add managed services tests job and adapt rosa & osde2e jobs to use it

diff --git a/jjb/dynamic/scale-ci-ms-rosa.yml b/jjb/dynamic/scale-ci-ms-rosa.yml
--- a/jjb/dynamic/scale-ci-ms-rosa.yml
+++ b/jjb/dynamic/scale-ci-ms-rosa.yml
@@ -5,7 +5,7 @@
       - shell: |+
           #!/bin/bash
           set -e
-          export RUN_FOLDER=$(date +%Y%m%d-%H%M%S)
+          export RUN_FOLDER=${BUILD_TIMESTAMP}
           echo "INFO: Getting perf-dept keys"
           [[ ! -d "${WORKSPACE}/perf-dept" ]] && git clone --depth=1 https://${GITHUB_TOKEN}@github.com/redhat-performance/perf-dept.git
           export PRIVATE_KEY=${WORKSPACE}/perf-dept/ssh_keys/id_rsa_pbench_ec2
@@ -48,7 +48,7 @@
             set -e
 
             # Parameter checks
-            WRAPPER_OPTIONS="--path ${REMOTE_WORKSPACE}/run-${RUN_FOLDER}"
+            WRAPPER_OPTIONS="--path ${REMOTE_WORKSPACE}/run-${RUN_FOLDER} --preserve-clusters"
 
             if [ -z ${ROSA_TOKEN} ] ; then
               echo "ERROR: Rosa token is required but it is not defined, exiting..."
@@ -65,11 +65,11 @@
 
             [ ! -z ${ROSA_ADDONS} ] && WRAPPER_OPTIONS+=" --rosa-addons ${ROSA_ADDONS}"
 
+            [ ! -z ${ROSA_INIT} ] && [ ${ROSA_INIT} == true ] && WRAPPER_OPTIONS+=" --rosa-init"
+
             [ ! -z ${ROSA_CLI} ] && WRAPPER_OPTIONS+=" --rosa-cli ${ROSA_CLI}"
 
             [ ! -z ${AWS_PROFILE} ] && WRAPPER_OPTIONS+=" --aws-profile ${AWS_PROFILE}"
-
-            [ ! -z ${CLEANUP_CLUSTERS} ] && [ ${CLEANUP_CLUSTERS} == "false" ] && WRAPPER_OPTIONS+=" --cleanup-clusters False"
 
             if [ ! -z ${ELASTICSEARCH_URL} ] ; then
               WRAPPER_OPTIONS+=" --es-url ${ELASTICSEARCH_URL}"
@@ -107,10 +107,21 @@
               fi
             fi
           ENDSSH
-
           # Getting run directory to archive as artifacts
           echo "INFO: Downloading ${REMOTE_WORKSPACE}/run-${RUN_FOLDER} folder from ${JUMP_HOST} to be archieved as artifacts"
           rsync -avzh --exclude='perfscale-managed-services' --exclude='rosa' -e "ssh ${OPTIONS} -i ${PRIVATE_KEY}" ${SSH_USER}@${JUMP_HOST}:${REMOTE_WORKSPACE}/run-${RUN_FOLDER}/ ${WORKSPACE}/artifacts/
+
+      - conditional-step:
+          condition-kind: boolean-expression
+          condition-expression: ${LAUNCH_TESTS}
+          steps:
+            - trigger-builds:
+                - project: "SCALE-CI-MS-TESTS"
+                  predefined-parameters: |
+                    REMOTE_FOLDER="${REMOTE_WORKSPACE}/run-${BUILD_TIMESTAMP}"
+                  current-parameters: true
+                  block: true
+
     concurrent: true
     description: OCM installation test on AWS using ROSA cli.
     disabled: false
@@ -202,10 +213,6 @@
           name: NUMBER_OF_CLUSTERS
           regex: '[0-9]*'
           msg: "Must be a number"
-      - bool:
-          default: true
-          description: "Mapped to <b>--cleanup-clusters</b>, cleanup any non-error state clusters upon test completion"
-          name: CLEANUP_CLUSTERS
       - validating-string:
           default: ''
           description: "Mapped to <b>--batch-size</b>, number of cluster to install on parallel"
@@ -245,10 +252,63 @@
             - DEBUG
       - bool:
           default: true
+          description: "Remove all created clusters at the end of the job"
+          name: CLEANUP_CLUSTERS
+      - bool:
+          default: false
+          description: "Launch <b>SCALE-CI-MS-TESTS</b> job with any kubeconfig file detected as artifact"
+          name: LAUNCH_TESTS
+      - bool:
+          default: true
           description: "Compress log files created before being downloaded in the Jenkins host as artifacts"
           name: COMPRESS_LOGS
     project-type: freestyle
     publishers:
+      - postbuildscript:
+          builders:
+            - role: BOTH
+              build-on:
+                - SUCCESS
+                - FAILURE
+                - UNSTABLE
+                - NOT_BUILT
+                - ABORTED
+              build-steps:
+                - conditional-step:
+                    condition-kind: boolean-expression
+                    condition-expression: ${CLEANUP_CLUSTERS}
+                    steps:
+                      - shell: |+
+                            #!/bin/bash
+                            set -e
+                            echo "INFO: Getting perf-dept keys"
+                            export RUN_FOLDER=${BUILD_TIMESTAMP}
+                            export PRIVATE_KEY=${WORKSPACE}/perf-dept/ssh_keys/id_rsa_pbench_ec2
+                            export OPTIONS="-o StrictHostKeyChecking=no -o ServerAliveInterval=1 -o ConnectionAttempts=100"
+                            [[ "${USE_PROXY}" == "true" ]] && OPTIONS+=" -o ProxyCommand=\"ssh -i ${PRIVATE_KEY} -W %h:%p ${PROXY_USER}@${PROXY_HOST}\""
+
+                            # Delete clusters after tests are executed
+                            echo "INFO: Delete clusters"
+                            ssh ${OPTIONS} -i ${PRIVATE_KEY} ${SSH_USER}@${JUMP_HOST} 'bash -s' <<ENDSSH
+                              set -e
+
+                              # Parameter checks
+                              WRAPPER_OPTIONS="--only-delete-clusters --path ${REMOTE_WORKSPACE}/run-${RUN_FOLDER}"
+                              if [ -z ${ROSA_TOKEN} ] ; then
+                                echo "ERROR: Rosa token is required but it is not defined, exiting..."
+                                exit 1
+                              else
+                                WRAPPER_OPTIONS+=" --rosa-token ${ROSA_TOKEN}"
+                              fi
+
+                              [ ! -z ${ROSA_CLI} ] && WRAPPER_OPTIONS+=" --rosa-cli ${ROSA_CLI}"
+                              [ ! -z ${LOG_LEVEL} ] && WRAPPER_OPTIONS+=" --log-level ${LOG_LEVEL}"
+                              [ ! -z ${LOG_FILE} ] && WRAPPER_OPTIONS+=" --log-file ${REMOTE_WORKSPACE}/run-${RUN_FOLDER}/${LOG_FILE}"
+
+                              # Wrapper execution
+                              echo "INFO: Running python3 ${REMOTE_WORKSPACE}/run-${RUN_FOLDER}/perfscale-managed-services/rosa/rosa-wrapper.py \${WRAPPER_OPTIONS}"
+                              python3 ${REMOTE_WORKSPACE}/run-${RUN_FOLDER}/perfscale-managed-services/rosa/rosa-wrapper.py \${WRAPPER_OPTIONS}
+                            ENDSSH
       - archive:
           artifacts: 'artifacts/**/*'
           excludes: 'artifacts/perfscale-managed-services/**/*,artifacts/rosa'
